### PR TITLE
Expose env var to force update failing ref tests

### LINKED ISSUE #8: Don't only rely on `isinteractive` for triggering the input prompt
So far this package decides whether or not an input prompt is to be triggered, by simply checking the result of `isinteractive()`. Thus, the input prompt is pretty much only displayed if the user is executing the tests from the REPL by calling `include("test/runtests.jl")`. @oxinabox made the argument that this is a bit restrictive, which I tend to agree with.

We had a brief chat in slack about it and thought of some other strategies:

- using a environment variable to detect CI
- using a environment variable to activate the input prompt
- read the callstack to see if `Pkg.test(...)` triggered the test run

### PR DESCRIPTION
**Pull request by IanButterworth**
I think this closes #8 

- [x] Add to docs

### CODE REVIEW

File: src/test_reference.jl [hunk 1]
```diff
@@ -181,6 +185,8 @@ function test_reference(
     end
 end
 
+force_update() = tryparse(Bool, get(ENV, "JULIA_REFERENCETESTS_UPDATE", "false")) === true
```
Comment (johnnychen94) [inline src/test_reference.jl:188]: good to know `tryparse`.

**Review by johnnychen94 — APPROVED** [review]

**Comment by IanButterworth** [comment]
@johnnychen94 I added some docs. Thanks for the invite to the org. I'm happy to merge, but can you just give the new docs a look. Thanks!

**Comment by IanButterworth** [comment]
Just noticed that the logic is wrong here. Just double-checking the fix

File: README.md [hunk 2]
```diff
@@ -84,6 +84,23 @@ compared as plain text. This is useful for a convenient
...
+Reference tests are typically used within a package's `test/runtests.jl`
+test suite. These tests are easy to run via `pkg> test` but
+the child process used within `pkg> test` is non-interactive, so the
+update prompt will not show if there are mismatches.
+
+To update references within a package test suite, there are two options:
+
+1. Set the environment variable `JULIA_REFERENCETESTS_UPDATE` to `"true"`
+   and run `pkg> test`, which will force update any non-matches. You can then
+   check changes to any git-tracked reference images before commit.
```
Comment (johnnychen94) [inline README.md:98]: Before this; we usually remove the entire `test/references` folder and track the git differences :)

But this is seems a better approach.

File: README.md [hunk 3]
```diff
@@ -84,6 +84,23 @@ compared as plain text. This is useful for a convenient
...
+2. Run the `test/runtests.jl` interactively. This may be easier using
```
Comment (johnnychen94) [inline README.md:99]: Maybe use an unordered list instead of the ordered one?

```suggestion
- Run the `test/runtests.jl` interactively. This may be easier using
```

**Review by johnnychen94 — APPROVED** [review]
Thanks for adding the docs. Much clearer!
